language: node_js
node_js:
 - "stable"
before_script: 
 - npm install
script:
 - npm run prod
branches:
  only:
  - master 
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    branch: master    
    tags: true  